### ISSUE TITLE
indradb_proto. Cannot import anything under `indradb_proto::indradb`

### ISSUE THREAD

**Issue by OZoneGuy** [indradb/indradb#239]
I added `indradb_proto` to my toml file, and I am trying to use it. My IDE can autocomplete the imports and the type definitions, but the compiler fails with `could not find 'indradb' in 'indradb_proto'`. Do I need to add both, `indradb-lib` and `indradb_proto` to my toml file?

For reference, I am trying to write a client for the DB server.

And here is my `Cargo.toml`:
```toml
[package]
name = "my-pkg"
version = "0.1.0"
edition = "2021"

[dependencies]
...
indradb-proto = { version = "3.0.1" }
```
