### ISSUE TITLE
MemoryDatastore read fail: Error: DeserializeAnyNotSupported

### ISSUE THREAD

**Issue by AndyJado** [indradb/indradb#258]
## In a word

MemoryDatastore `read()` a db with `vertex & vertex properties` fail, same logic, rockdb works just fine

## version info

tested both on a ubunto 20.04 and a macos13.

```toml
indradb-lib = { version = "*", features = ["rocksdb-datastore"] }
serde = { version = "^1.0.57", features = ["derive"] }
serde_json = "^1.0.57"
byteorder = "^1.4.2"
lazy_static = "^1.4.0"
chrono = { version = "0.4.22", features = ["serde"] }
bincode = "^1.3.3"
tempfile = "^3.2.0"
uuid = { version = "^1.1.2", features = ["v1", "serde"] }
```
## describe

say I sync a database with `vertex_properties` empty, It can read fine, however if I insert bulk and debug the db:

```
MemoryDatastore {
    datastore: RwLock {
        data: InternalMemoryDatastore {
            vertices: {
                7bcb3d52789411ed8000000000000000: Identifier(
                    "sample",
                ),
            },
            edges: {},
            reversed_edges: {},
            vertex_properties: {
                (
                    7bcb3d52789411ed8000000000000000,
                    Identifier(
                        "idsdad",
                    ),
                ): Json(
                    Bool(true),
                ),
            },
            edge_properties: {},
            property_values: {},
        },
        poisoned: false,
        ..
    },
    path: Some(
        "image.bincode",
    ),
}
```
then write is fine, it just cannot be `read()` anymore and give the Error in issue.
